### ISSUE TITLE
CODE RELEASE

### ISSUE THREAD

**Issue by rspezialetti** [Yan-Xia/ASFM-Net#1]
Hi,

thank you for the nice work. When will the code be released?

Bests,
Riccardo

**Comment by YaqiXia** [comment]
Hi, 

sorry for the late reply! During this time, I was busy adapting to the new working environment and research field, so I have not updated our code in time. I will deal with it in the near future.

**Comment by YaqiXia** [comment]
> Hi,
> 
> thank you for the nice work. When will the code be released?
> 
> Bests, Riccardo

Hi,

sorry for the late reply! During this time, I was busy adapting to the new working environment and research field, so I have not updated our code in time. I will deal with it in the near future.
