### ISSUE TITLE
The publish time of this work

### ISSUE THREAD

**Issue by leonardozcm** [Yan-Xia/ASFM-Net#3]
hi, it's inspired when I heard that your work has achieved SOTA, i wonder would you mind publishing the code of this paper and when if so? thanks a lot!

**Comment by YaqiXia** [comment]
> hi, it's inspired when I heard that your work has achieved SOTA, i wonder would you mind publishing the code of this paper and when if so? thanks a lot!

Hi,

sorry for the late reply! During this time, I was busy adapting to the new working environment and research field, so I have not updated our code in time. I will deal with it in the near future.
